### ISSUE TITLE
[e-translate]: GET language pairs

### ISSUE THREAD

**Issue by ghsnd** [freme-project/Broker#153] opened 2016-01-14 13:56 UTC
A handy feature for a future release: possibility to get the language pairs by sending a (GET) request. This allows tools (e.g., our CKEditor plugin ;) ) to automatically get the possible language pairs, which has to be hardcoded at this moment.

**Comment by jnehring** [comment] 2016-02-10 15:56
@andish does an Tilde API endpoint exist that sends the list of language pairs?

**Comment by andish** [comment] 2016-02-11 10:46
Not yet. but I will create it, after review. It will serve a list of available translation systems: source Lang, target Lang, domain, system id.

**Comment by andish** [comment] 2016-09-22 08:51
Duplicate of https://github.com/freme-project/e-services/issues/20

**Closed by andish** 2016-09-22 08:51 UTC
Labels: enhancement
