### ISSUE TITLE
json-ld structure changes

### ISSUE THREAD

**Issue by xFran** [freme-project/Broker#136] opened 2015-11-13 14:02 UTC
I want to integrate e-terminology in Wripl's application. So I'm doing some tests in order to understand how is working, what data do I need and what don't.
This is the json-ld transformed to array. I'm sure everybody understand it. 
```
Array
(
// General info request
    [test_string] => Madrid is home to two world-famous football clubs
    [params] => Zend\Stdlib\Parameters Object
        (
            [storage:ArrayObject:private] => Array
                (
                    [informat] => text
                    [outformat] => json-ld
                    [source-lang] => en
                    [target-lang] => en
                    [mode] => annotation
                    [collection] => 
                )

        )

    [response_status_code] => 200
// ...

This is the actual response:

    [body_content] => Array
        (
            [0] => Array
                (
                    [@id] => _:b0
                    [label] => Array
                        (
                            [@language] => en
                            [@value] => Madrid
                        )

                    [taConfidence] => 0.8109
                )

            [1] => Array
                (
                    [@id] => _:b1
                    [label] => Array
                        (
                            [@language] => en
                            [@value] => two
                        )

                    [itsrdf:taConfidence] => 0
                )

            [2] => Array
                (
                    [@id] => _:b2
                    [label] => Array
                        (
                            [@language] => en
                            [@value] => football club
                        )

                    [itsrdf:taConfidence] => 1
                )

            [3] => Array
                (
                    [@id] => _:b3
                    [label] => Array
                        (
                            [0] => Array
                                (
                                    [@language] => en
                                    [@value] => Home
                                )

                            [1] => Array
                                (
                                    [@language] => en
                                    [@value] => home
                                )

                        )

                    [taConfidence] => 0.234
                )

            [4] => Array
                (
                    [@id] => _:b4
                    [label] => Array
                        (
                            [@language] => en
                            [@value] => famous
                        )

                    [taConfidence] => 0.3555
                )

            [5] => Array
                (
                    [@id] => _:b5
                    [label] => Array
                        (
                            [0] => Array
                                (
                                    [@language] => en
                                    [@value] => World
                                )

                            [1] => Array
                                (
                                    [@language] => en
                                    [@value] => world
                                )

                        )

                    [taConfidence] => 0.0801
                )
... // I removed some not relevant elements for this issue
)
```

In my case I need to make an array with term name and confidence.
Something like this
```
[
    'term' => 'Madrid',
    'confidence' => 0.8109
]
```
__Issues__

When I'm looking at the response array I see 
[itsrdf:taConfidence] and [taConfidence] My next question is which is what? (rhetoric)
I need the terms but the format of the label sometimes is just a simple array and sometimes multidimensional array.
If I use this text "Madrid is home to two world-famous football clubs, Real Madrid and Atlético de Madrid." we can see that Madrid show up 3 times and in my response I will have 3 Madrid terms which are 3 arrays more each array with his items... Way too many duplicate data.

@andish was kind enough to help me with some suggestions but all API's by default are using json and I need it for python, php, javascript and last but not least cross-domain calls.
Maybe using json instead json-ld keeping in mind that almost all app in these days it's a web application is better. 

I'd like to hear more opinions. Thank you.

**Comment by andish** [comment] 2015-11-13 14:22
Actually here was 2 issues raised:
1) **Using the prefixes.** For some categories there are prefixes, but most of categories have not:
![image](https://cloud.githubusercontent.com/assets/11315268/11147820/4eb996b0-8a21-11e5-965d-3ccecbb3a23c.png)
2) **Array and array of arrays**. If in turtle we have annotationUnit with multiple labels, then in json-ld there is aditional array level inside.
this is in rdf/turtle:
```turtle
<http://freme-project.eu/#char=22,27>
        a                     nif:RFC5147String ;
        nif:anchorOf          "world"@en ;
        nif:annotationUnit    [ rdfs:label           "World"@en , "world"@en ;
                                itsrdf:taConfidence  0.0801
                              ] ;
```
and ir convert like this in json-ld:
```json
 [label] => Array
                        (
                            [0] => Array
                                (
                                    [@language] => en
                                    [@value] => World
                                )

                            [1] => Array
                                (
                                    [@language] => en
                                    [@value] => world
                                )

                        )
```
And if there is only one label in turtle, than there is no array:
```json
 [label] => Array
                        (
                            [@language] => en
                            [@value] => famous
                        )
```

I think this ( 2. issue) is 'as designed' for json, but @xFran has a difficulty to use that.

**Comment by jnehring** [comment] 2015-11-17 09:10
I had difficulties to reproduce the issues you reported. I did this CURL with the text you provided

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.4/e-terminology/tilde?input=Madrid%20is%20home%20to%20two%20world-famous%20football%20clubs&informat=text&outformat=json-ld&source-lang=en&target-lang=de&mode=full"
```

and get [this JSON LD](https://github.com/freme-project/Broker/files/36458/eterminology-json-ld.txt) as response.

> When I'm looking at the response array I see [itsrdf:taConfidence] and [taConfidence] My next question is which is what? (rhetoric)

[itsrdf:taConfidence] stores the confidence values that you are interested in. [taConfidence] stores the URI of the "taConfidence" variable. You can ignore this. In your response you have multiple occurence "taConfidence" with numeric values which is indeed confusing. In my output there is only one occurence of "taConfidence" with a string value.

> I need the terms but the format of the label sometimes is just a simple array and sometimes multidimensional array.

Sorry as @andish said you have to deal with both formats. But this should only be a matter of a simple "if / else" statement and a few lines of code.

> Maybe using json instead json-ld keeping in mind that almost all app in these days it's a web application is better.

JSON-LD is actually JSON. I can see that you are not interested in all the information you get back from e-Terminology but other users might be interested in it. The output is complex for good reasons and therefore we will stick to JSON-LD. But I will discuss with others if we can introduce a more simple output format.

The big question I have right now is that that my output in JSON-LD has different information from your "json-ld transformed to array". Its not only about ta:Confidence with numeric or string values. Also I cannot see Madrid spotted as a term. Can you post your JSON-LD before it was transformed to an array? And also the full HTTP request you performed to FREME API?

**Comment by koidl** [comment] 2015-11-17 11:38
Hi Jan 

Thanks for the response. Our main concern is the usefulness of the return. Currently the return is far to complex for our use case and has a lot of redundant information. 

However there might be multiple issues here that I don't understand yet - I hope you can help. All the below is in no way to criticize I just need to understand some basics:

- What are the other use cases that require this more complex return? The last thing we want to do is create complexity for other by making the return more simple for our use case

- We are not using e-terminology for translation of terms. At the moment we need it to extract terms in one language (english) and without knowing the domain at design time. Can it be that e-terminology itself is not built for this purpose? For example I added the sentence "Madrid is home to two world-famous football clubs" into TaaS on tildes page and every word except "is" and "to" was annotated. I wonder why "two" for example is extracted as term?

- You state that we can use a simple if then lookup which might work with one sentence. I tested a longer text (not even long - one paragraph):

"Madrid, Spain's central capital, is a city of elegant boulevards and expansive, manicured parks such as the Buen Retiro. It’s renowned for its rich repositories of European art, including the Prado Museum’s works by Goya, Velázquez and other Spanish masters. The heart of old Hapsburg Madrid is the portico-lined Plaza Mayor, and nearby is the baroque Royal Palace and Armory, displaying historic weaponry."

The return is very long and complex. Please let me know what that simple if-then statement would look like in your mind. Keep in mind I haven't coded in a while therefore its surely on my side that I don't see the simplicity. Also keep in mind the statement has to work with any return from e-terminology. I therefore assume no matter how long the sent body text is, the structure of the return remains the same - it just gets very long thats all?

- On a more general note I am slightly concerned about the current "one return serves them all" approach. Is this the best practise? I am just slightly concerned that if other use cases demands a change in the data structure all others have to change their logic because of that. Would it not be much easier to do this on the API side so that if something changes that effects all it can be fixed there. Not sure - would be good to hear your opinion on this.

**Comment by fsasaki** [comment] 2015-11-17 12:13
Hi Kevin,
on 
"if other use cases demands a change in the data structure all others have to change their logic because of that. ": agree, though I don't see other use cases asking for changes. Who do you have in mind?
In general on this thread, as said via mail, sitting together coding this would probably solve the problem in 1/2 day. But let's see how this thread moves forward.

**Comment by koidl** [comment] 2015-11-17 12:17
Thanks Felix. I understand. I need to know more about the other use cases then (I asked Jan further up) and why the other use cases may hinder a more simpler return. I guess there must be a reason/history why the return is so complex. Being aware that others may need the return as is - I just want to understand the basics before suggesting solutions/changes.

**Comment by jnehring** [comment] 2015-11-17 12:19
> What are the other use cases that require this more complex return? The last thing we want to do is create complexity for other by making the return more simple for our use case

The result is so complex because it is in NIF. The main reason for using NIF is interoperability with other tools. E.g. we could do a very simple and extensive evaluation of FREME NER by using off-thge-shelf tooling because we follow the NIF conventions.

For consumption by humans I propose the format turtle. The JSON-LD is not the easiest to read. But it is not impossible to read, I think from looking at the JSON-LD it is possible to extract the two information you are interested in - terms and confidence values, also without NIF background knowledge. I think writing a script that extracts the most important terms is a matter of a few lines of code.

But I see that the results are confusing. I propose to add an easier output format to each e-Service. This easy output format stores only the most important information about each annotation in JSON. We need to implement it for each e-Service e-Terminology, e-Translation and e-Entity separately. When you agree that this is useful then we can open a new GitHub issue for this feature. But it will take at least some weeks to implement such feature. In the meantime I can offer you help you out with a small PHP script that parses the output of e-Terminology and extracts only terms and confidence values.

>  I added the sentence "Madrid is home to two world-famous football clubs" into TaaS on tildes page and every word except "is" and "to" was annotated.

This should be discussed with @andish because I do not know how e-Terminology works. This issue is about issues with the complexity of NIF and JSON LD so please open a new issue to discuss usefulness of the e-Terminology output.

**Comment by koidl** [comment] 2015-11-17 12:21
Thanks Jan - yes sounds great. How do you want to proceed best. Will you open a separate issue?

**Comment by jnehring** [comment] 2015-11-17 12:46
I created https://github.com/freme-project/technical-discussion/issues/89 for the simple JSON format.

Do you need the PHP script I proposed? I think you should first try again to write it yourself. I think I would need some days, I think I can deliver it early next week.

About the usefulness of e-Terminology output: Please create an issue yourself and assign it to @andish .

**Comment by xFran** [comment] 2015-11-17 12:57
This is my http request object:
```
Zend\Http\Request Object
(
    [method:protected] => POST
    [uri:protected] => Zend\Uri\Http Object
        (
            [validHostTypes:protected] => 19
            [user:protected] => 
            [password:protected] => 
            [scheme:protected] => http
            [userInfo:protected] => 
            [host:protected] => api.freme-project.eu
            [port:protected] => 
            [path:protected] => /current/e-terminology/tilde
            [query:protected] => 
            [fragment:protected] => 
        )

    [queryParams:protected] => Zend\Stdlib\Parameters Object
        (
            [storage:ArrayObject:private] => Array
                (
                    [informat] => text
                    [outformat] => json-ld
                    [source-lang] => en
                    [target-lang] => en
                    [mode] => annotation
                    [collection] => 
                )

        )

    [postParams:protected] => 
    [fileParams:protected] => 
    [version:protected] => 1.1
    [headers:protected] => Zend\Http\Headers Object
        (
            [pluginClassLoader:protected] => Zend\Http\HeaderLoader Object
                (
                    [plugins:protected] => Array
                        (
                            [accept] => Zend\Http\Header\Accept
                            [acceptcharset] => Zend\Http\Header\AcceptCharset
                            [acceptencoding] => Zend\Http\Header\AcceptEncoding
                            [acceptlanguage] => Zend\Http\Header\AcceptLanguage
                            [acceptranges] => Zend\Http\Header\AcceptRanges
                            [age] => Zend\Http\Header\Age
                            [allow] => Zend\Http\Header\Allow
                            [authenticationinfo] => Zend\Http\Header\AuthenticationInfo
                            [authorization] => Zend\Http\Header\Authorization
                            [cachecontrol] => Zend\Http\Header\CacheControl
                            [connection] => Zend\Http\Header\Connection
                            [contentdisposition] => Zend\Http\Header\ContentDisposition
                            [contentencoding] => Zend\Http\Header\ContentEncoding
                            [contentlanguage] => Zend\Http\Header\ContentLanguage
                            [contentlength] => Zend\Http\Header\ContentLength
                            [contentlocation] => Zend\Http\Header\ContentLocation
                            [contentmd5] => Zend\Http\Header\ContentMD5
                            [contentrange] => Zend\Http\Header\ContentRange
                            [contenttransferencoding] => Zend\Http\Header\ContentTransferEncoding
                            [contenttype] => Zend\Http\Header\ContentType
                            [cookie] => Zend\Http\Header\Cookie
                            [date] => Zend\Http\Header\Date
                            [etag] => Zend\Http\Header\Etag
                            [expect] => Zend\Http\Header\Expect
                            [expires] => Zend\Http\Header\Expires
                            [from] => Zend\Http\Header\From
                            [host] => Zend\Http\Header\Host
                            [ifmatch] => Zend\Http\Header\IfMatch
                            [ifmodifiedsince] => Zend\Http\Header\IfModifiedSince
                            [ifnonematch] => Zend\Http\Header\IfNoneMatch
                            [ifrange] => Zend\Http\Header\IfRange
                            [ifunmodifiedsince] => Zend\Http\Header\IfUnmodifiedSince
                            [keepalive] => Zend\Http\Header\KeepAlive
                            [lastmodified] => Zend\Http\Header\LastModified
                            [location] => Zend\Http\Header\Location
                            [maxforwards] => Zend\Http\Header\MaxForwards
                            [pragma] => Zend\Http\Header\Pragma
                            [proxyauthenticate] => Zend\Http\Header\ProxyAuthenticate
                            [proxyauthorization] => Zend\Http\Header\ProxyAuthorization
                            [range] => Zend\Http\Header\Range
                            [referer] => Zend\Http\Header\Referer
                            [refresh] => Zend\Http\Header\Refresh
                            [retryafter] => Zend\Http\Header\RetryAfter
                            [server] => Zend\Http\Header\Server
                            [setcookie] => Zend\Http\Header\SetCookie
                            [te] => Zend\Http\Header\TE
                            [trailer] => Zend\Http\Header\Trailer
                            [transferencoding] => Zend\Http\Header\TransferEncoding
                            [upgrade] => Zend\Http\Header\Upgrade
                            [useragent] => Zend\Http\Header\UserAgent
                            [vary] => Zend\Http\Header\Vary
                            [via] => Zend\Http\Header\Via
                            [warning] => Zend\Http\Header\Warning
                            [wwwauthenticate] => Zend\Http\Header\WWWAuthenticate
                        )

                )

            [headersKeys:protected] => Array
                (
                    [0] => contenttype
                )

            [headers:protected] => Array
                (
                    [0] => Zend\Http\Header\ContentType Object
                        (
                            [value] => text/plain; charset=UTF-8
                        )

                )

        )

    [metadata:protected] => Array
        (
        )

    [content:protected] => Madrid is home to two world-famous football clubs, Real Madrid and AtlÃ©tico de Madrid.
)
```
This is the response: [eterminology-json-ld.txt](https://github.com/freme-project/Broker/files/36650/eterminology-json-ld.txt)

>  In the meantime I can offer you help you out with a small PHP script that parses the output of e-Terminology and extracts only terms and confidence values.
> Do you need the PHP script I proposed? 

Please @jnehring ... if I wouldn't know you, I could start thinking, probably, that's an insult :) I'm sure is NOT. And I'm sure I can use easyRDF lib or make a simple loop or some if statements more end remove 99% of the data from the response witch I don't need.

Let's focus on KISS principle programming and keep things clean if is posible. If not, just let me know.

Thank you all.

**Comment by jnehring** [comment] 2015-11-17 13:07
> if I wouldn't know you, I could start thinking, probably, that's an insult :) 

Sorry it was not meant as an insult. I just wanted to offer help so you can quickly move forward.

> This is the response: eterminology-json-ld.txt

This response looks alright to me. In the JSON LD I cannot see madrid being spotted as a term and I cannot see a confidence value using the attribute "taConfidence". These two information where in the output of your "json-ld transformed array". So I assume that something went wrong during transformation.

So coming back to your original questions:

> [itsrdf:taConfidence] and [taConfidence] My next question is which is what?

So you can use itsrdf:taConfidence. OK?

> I need the terms but the format of the label sometimes is just a simple array and sometimes multidimensional array.

Already answered above.

> If I use this text "Madrid is home to two world-famous football clubs, Real Madrid and Atlético de Madrid." we can see that Madrid show up 3 times and in my response I will have 3 Madrid terms which are 3 arrays more each array with his items... Way too many duplicate data.

Answered above.

So any more open questions?

**Comment by xFran** [comment] 2015-11-17 13:15
Ups!! my bad. Wrong file.
This is the good one. 
[eterminology-json-ld.txt](https://github.com/freme-project/Broker/files/36672/eterminology-json-ld.txt)

> Sorry it was not meant as an insult. 
I know that @jnehring no worries. I knew it from the beginning.

Crystal clear. I will use [itsrdf:taConfidence] for the term confidence.

Thank you.

**Closed** 2015-11-18 13:57 UTC
Labels: enhancement
